### ISSUE TITLE
HU7: Como desarrollador, quiero que existan distintas rutas en el microservicio para que cualquier usuario pueda acceder a los distintos recursos disponibles

### ISSUE THREAD

**Issue by currobeltran** [currobeltran/F1-Predictor#71]
Para solucionar este problema, será necesario disponer de una serie de objetos que representen los recursos y definir distintos métodos para los mismos con el objetivo de acceder a ellos realizando una acción determinada. Los issues a solucionar para esta historia de usuario son los siguientes:

- [Es necesario crear recursos](https://github.com/currobeltran/F1-Predictor/issues/72)
- [Es necesario crear métodos para acceder a recursos](https://github.com/currobeltran/F1-Predictor/issues/73)
- [Es necesario crear un log](https://github.com/currobeltran/F1-Predictor/issues/74)

**Comment by JJ** [comment]
No es una HU. El usuario no tiene por qué saber nada de los detalles de implementación.
